// Auto-generated by scripts/fetch-projects.mjs. Do not edit by hand.
// Run `pnpm projects:fetch` to refresh.

import type { Project } from './portfolio'

export const projects: readonly Project[] = [
  {
    "slug": "kkulebaev/x-tweet-tracker-forwarder",
    "title": "x-tweet-tracker-forwarder",
    "description": "Voyager forwarder: Redis Streams → Telegram posting worker",
    "codeHref": "https://github.com/kkulebaev/x-tweet-tracker-forwarder"
  },
  {
    "slug": "kkulebaev/birthday-reminder-bot",
    "title": "birthday-reminder-bot",
    "description": "A calm Telegram-first assistant for remembering important birthdays and important dates",
    "codeHref": "https://github.com/kkulebaev/birthday-reminder-bot"
  },
  {
    "slug": "kkulebaev/orbit-todo-bot",
    "title": "orbit-todo-bot",
    "description": "Telegram TODO bot with inline buttons. Built with Node.js + grammY, backed by PostgreSQL via Prisma.",
    "codeHref": "https://github.com/kkulebaev/orbit-todo-bot"
  },
  {
    "slug": "kkulebaev/x-tweet-tracker-api",
    "title": "x-tweet-tracker-api",
    "description": "Voyager API: store tracked X (Twitter) posts and expose admin endpoints",
    "codeHref": "https://github.com/kkulebaev/x-tweet-tracker-api"
  },
  {
    "slug": "kkulebaev/weekly-headlines-cron",
    "title": "weekly-headlines-cron",
    "description": "",
    "codeHref": "https://github.com/kkulebaev/weekly-headlines-cron"
  },
  {
    "slug": "kkulebaev/tgstat-to-ads",
    "title": "tgstat-to-ads",
    "description": "Weekly TGStat stats → Telegram post (widget + caption + CTA), with Postgres state.",
    "codeHref": "https://github.com/kkulebaev/tgstat-to-ads"
  },
  {
    "slug": "kkulebaev/telegram-notify-service",
    "title": "telegram-notify-service",
    "description": "Tiny HTTP service to send notifications to Telegram",
    "codeHref": "https://github.com/kkulebaev/telegram-notify-service"
  },
  {
    "slug": "kkulebaev/x-tweet-tracker-cron",
    "title": "x-tweet-tracker-cron",
    "description": "Voyager cron worker: sync new X (Twitter) posts into the API database",
    "codeHref": "https://github.com/kkulebaev/x-tweet-tracker-cron"
  },
  {
    "slug": "kkulebaev/telegram-channel-collector",
    "title": "telegram-channel-collector",
    "description": "Webhook service to store Telegram channel posts in Postgres",
    "codeHref": "https://github.com/kkulebaev/telegram-channel-collector"
  },
  {
    "slug": "kkulebaev/x-tweet-tracker-bot",
    "title": "x-tweet-tracker-bot",
    "description": "Voyager Telegram bot: admin UI for managing tracked accounts (reads from API)",
    "codeHref": "https://github.com/kkulebaev/x-tweet-tracker-bot"
  }
]
